### ISSUE TITLE
Error: could not automatically determine read pair orientation

### ISSUE THREAD

**Issue by atiaamin2019** [rrwick/Polypolish#17] opened 2023-10-13 18:18 UTC
Hello,

I got this error while trying to run 
`polypolish_insert_filter.py --in1 alignments_1.sam --in2 alignments_2.sam --out1 filtered_1.sam --out2 filtered_2.sam`
Could you please help me to solve this issue?
Thanks!

**Comment by rrwick** [comment] 2023-10-16 05:07
You can manually specify the read orientation using the `--orientation` option, which will make the error go away.

However, it's strange that you got that error. Most paired-end read sets should have a consistent orientation, allowing the script to automatically determine it. Can you check that nothing went wrong in your initial alignment (the generation of the `alignments_1.sam` and `alignments_2.sam` files)?

**Comment by rrwick** [comment] 2024-01-15 03:24
I'm closing this issue because it's a few months old and I've just reimplemented insert-size filtering in Rust for [Polypolish v0.6.0](https://github.com/rrwick/Polypolish/releases/tag/v0.6.0). But please let me know if you're still running into this problem!

**Closed as completed by rrwick** 2024-01-15 03:24 UTC

**Comment by Laura-Schnell** [comment] 2024-06-11 22:15
Hi There! I have been running into this issue with some of my assemblies. I tried rerunning the alignments and also tried setting a manual orientation. When I specify an orientation, I get "Error: no read pairs available to determine insert size thresholds". It seems for some reason that it isn't picking up any read pairs in my files? 

"Finding insert size thresholds (2024-06-11 15:46:14)
    Read pairs with exactly one alignment per read are used to determine the
orientation and insert size thresholds for the read set.

fr: 0 pairs
rf: 0 pairs
ff: 0 pairs
rr: 0 pairs"

I used trimgalore to filter my illumina reads prior to this and I have redone that in case there was some issue but am still getting the error. However, other samples with the same workflow were successful. Do you have any ideas?

**Comment by rrwick** [comment] 2024-06-12 00:11
Hi Laura,

That’s strange… Polypolish isn’t able to find any read pairs.

One hypothesis: do the reads in each pair have the same name in the SAM file? They should, e.g. if the first-in-pair read is named ‘abc’ in the SAM, then the second-in-pair read should have that same name.

See this section of the FAQ:
https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#can-i-use-bowtie2-instead-of-bwa-mem

Ryan

**Comment by Laura-Schnell** [comment] 2024-06-14 15:36
Hi Ryan! Thank you for your reply. I checked and the SAM files have the same names (I was using bwa-mem). I thought perhaps the short-reads were not aligning to my long-read assembly so I tried to map to a unicycler assembly and am having the same error. I'll keep investigating!

**Comment by rrwick** [comment] 2024-06-14 19:18
If there aren't data privacy issues, could you upload small versions of your SAM files to this GitHub issues so I can take a look?

Just 100 lines or so would be enough:
```
head -n100 alignments_1.sam > small_1.sam
head -n100 alignments_2.sam > small_2.sam
```

**Comment by Laura-Schnell** [comment] 2024-06-19 21:52
Thank you! It cuts off the actual reads in this (they show up around line 202) but hopefully this gives some info! I can upload more if that is better 
[small_1..sam.txt](https://github.com/user-attachments/files/15906173/small_1.sam.txt)
[small_2.sam.txt](https://github.com/user-attachments/files/15906174/small_2.sam.txt)

I have been comparing the files to other ones and I think the names actually are different and I was looking at the wrong part of the sam file. I'm sorry! I will try to figure out why bwa is doing this. Here is a screenshot for reference. 
<img width="1710" alt="Screenshot 2024-06-19 at 3 59 55 PM" src="https://github.com/rrwick/Polypolish/assets/144365534/dc0fcb18-2aa2-4bbb-91dc-4b1943fa33fe">

**Comment by rrwick** [comment] 2024-06-21 04:17
Yeah, if the read names don't match, that's almost certainly the cause of the problem. Perhaps the problem traces back to the FASTQ files?

**Comment by Laura-Schnell** [comment] 2024-06-24 15:42
I am sorry for not realizing this was the issue sooner! Thank you so much for your help!
